
name: otonavigasyon
description: Araba içi kullanılmak üzere GPS ve harita uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0

flutter:
  uses-material-design: true
